//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myyntihallinta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyyntiDBEntities : DbContext
    {
        public MyyntiDBEntities()
            : base("name=MyyntiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakas> Asiakkaat { get; set; }
        public virtual DbSet<Tilaus> Tilaukset { get; set; }
        public virtual DbSet<TilausRivi> TilausRivit { get; set; }
        public virtual DbSet<Tuote> Tuotteet { get; set; }
    }
}
