//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myyntihallinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilaus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tilaus()
        {
            this.TilausRivi = new HashSet<TilausRivi>();
        }
    
        public int tilaus_id { get; set; }
        public Nullable<int> asiakas_id { get; set; }
        public Nullable<System.DateTime> tilausPvm { get; set; }
        public Nullable<System.DateTime> toimitusPvm { get; set; }
        public Nullable<decimal> tilaussumma { get; set; }
    
        public virtual Asiakas Asiakas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TilausRivi> TilausRivi { get; set; }
    }
}
