//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myyntihallinta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TilausRivi
    {
        public int tilaus_id { get; set; }
        public int rivinro { get; set; }
        public int tuote_id { get; set; }
        public Nullable<int> tilausLkm { get; set; }
        public Nullable<decimal> ahinta { get; set; }
        public Nullable<decimal> alennus { get; set; }
    
        public virtual Tilaus Tilaus { get; set; }
        public virtual Tuote Tuote { get; set; }
    }
}
